[build]
publish = "public"
command = "npm run build"
functions = "lambda"

[build.environment]
NODE_VERSION = "12.16.1"
NPM_VERSION = "6.13.4"

[[headers]]
for = "/static/*"

[headers.values]
Cache-Control = "public, max-age=360000"
